export type SkillCategory = "frontend" | "ai" | "education";

export type SkillBookData = {
  id: string;
  title: string;
  shortLabel: string;
  category: SkillCategory;
  kind: "skill" | "education";
  level: string;
  summary: string;
  experience: string[];
  tags: string[];
  tone: "blue" | "peach" | "indigo" | "sage" | "stone" | "mustard" | "violet" | "terracotta";
  height: number;
};

export const shelfLabels: Record<SkillCategory, string> = {
  frontend: "build",
  ai: "AI + research",
  education: "education + career",
};

export const skillBooks: SkillBookData[] = [
  {
    id: "react",
    title: "React",
    shortLabel: "React",
    category: "frontend",
    kind: "skill",
    level: "Experienced",
    summary: "I use React to build interactive products, portals, and reusable interface systems.",
    experience: ["Contributor portals", "Marketplace interfaces", "Complex forms", "API-driven UI"],
    tags: ["React", "Components", "State", "REST APIs"],
    tone: "blue",
    height: 126,
  },
  {
    id: "astro",
    title: "Astro",
    shortLabel: "Astro",
    category: "frontend",
    kind: "skill",
    level: "Production work",
    summary: "I build fast content and corporate platforms with Astro and headless content workflows.",
    experience: ["Corporate websites", "Job platforms", "Headless CMS work", "Performance-focused builds"],
    tags: ["Astro", "Islands", "CMS", "Performance"],
    tone: "peach",
    height: 116,
  },
  {
    id: "typescript",
    title: "TypeScript",
    shortLabel: "TypeScript",
    category: "frontend",
    kind: "skill",
    level: "Daily toolkit",
    summary: "TypeScript helps me keep larger frontends predictable, maintainable, and easier to evolve.",
    experience: ["Typed component APIs", "Data modelling", "Safer refactors", "Next.js applications"],
    tags: ["TypeScript", "Types", "Architecture"],
    tone: "indigo",
    height: 132,
  },
  {
    id: "tailwind",
    title: "Tailwind CSS",
    shortLabel: "Tailwind",
    category: "frontend",
    kind: "skill",
    level: "Experienced",
    summary: "I use Tailwind to turn design systems into consistent, responsive product interfaces.",
    experience: ["Responsive systems", "Design tokens", "Component styling", "Rapid UI iteration"],
    tags: ["Tailwind", "CSS", "Responsive UI"],
    tone: "sage",
    height: 120,
  },
  {
    id: "wordpress",
    title: "WordPress",
    shortLabel: "WordPress",
    category: "frontend",
    kind: "skill",
    level: "Advanced implementation",
    summary: "I use WordPress beyond page building, including structured content and custom product workflows.",
    experience: ["Custom post types", "ACF content systems", "Custom APIs", "Marketplace workflows"],
    tags: ["WordPress", "ACF", "APIs", "CMS"],
    tone: "indigo",
    height: 138,
  },
  {
    id: "ai",
    title: "Artificial Intelligence",
    shortLabel: "AI",
    category: "ai",
    kind: "skill",
    level: "Research + applied interest",
    summary: "My AI experience comes from machine-learning research and practical product experimentation.",
    experience: ["BERT fine-tuning", "NLP research", "Federated learning", "AI-assisted product ideas"],
    tags: ["AI", "ML", "NLP", "Research"],
    tone: "violet",
    height: 142,
  },
  {
    id: "python",
    title: "Python",
    shortLabel: "Python",
    category: "ai",
    kind: "skill",
    level: "Research toolkit",
    summary: "I use Python for machine-learning experiments, data preparation, and research workflows.",
    experience: ["Model experiments", "Data preparation", "Research notebooks", "NLP pipelines"],
    tags: ["Python", "Data", "ML"],
    tone: "mustard",
    height: 122,
  },
  {
    id: "bert-nlp",
    title: "BERT / NLP",
    shortLabel: "BERT",
    category: "ai",
    kind: "skill",
    level: "Research exposure",
    summary: "I explored transformer-based language models through BERT spam-detection research.",
    experience: ["Text preprocessing", "Fine-tuning", "Spam classification", "Evaluation workflows"],
    tags: ["BERT", "NLP", "Transformers"],
    tone: "terracotta",
    height: 130,
  },
  {
    id: "federated-learning",
    title: "Federated Learning",
    shortLabel: "Federated",
    category: "ai",
    kind: "skill",
    level: "Research interest",
    summary: "I am interested in privacy-preserving ML and learning across distributed data sources.",
    experience: ["Federated concepts", "Privacy-aware ML", "Distributed learning", "Research review"],
    tags: ["Federated ML", "Privacy", "Research"],
    tone: "sage",
    height: 138,
  },
  {
    id: "msc",
    title: "MSc Computational Sciences",
    shortLabel: "MSc",
    category: "education",
    kind: "education",
    level: "Postgraduate study",
    summary: "Advanced study connecting computing, research methods, and analytical problem solving.",
    experience: ["Computational thinking", "Research methods", "Applied analysis", "Independent study"],
    tags: ["MSc", "Computing", "Research"],
    tone: "blue",
    height: 142,
  },
  {
    id: "bsc",
    title: "BSc (Hons) Information Technology",
    shortLabel: "BSc IT",
    category: "education",
    kind: "education",
    level: "SLIIT",
    summary: "A foundation in software engineering, information technology, and practical application development.",
    experience: ["Software engineering", "Web development", "Databases", "Team projects"],
    tags: ["BSc (Hons)", "IT", "SLIIT"],
    tone: "peach",
    height: 136,
  },
  {
    id: "research",
    title: "Research",
    shortLabel: "Research",
    category: "education",
    kind: "education",
    level: "AI + NLP",
    summary: "Research work focused on language models, classification, and privacy-aware machine learning.",
    experience: ["BERT spam detection", "NLP experimentation", "Federated learning", "Technical writing"],
    tags: ["Research", "BERT", "NLP"],
    tone: "violet",
    height: 126,
  },
  {
    id: "experience",
    title: "Software Engineering",
    shortLabel: "5+ years",
    category: "education",
    kind: "education",
    level: "Professional experience",
    summary: "More than five years delivering web products across frontend, CMS, and business-platform work.",
    experience: ["30+ shipped projects", "Frontend systems", "Client delivery", "Product refinement"],
    tags: ["Engineering", "Delivery", "Products"],
    tone: "stone",
    height: 132,
  },
];
