export type SkillCategory = "frontend" | "ai" | "education";

export type SkillBookData = {
  id: string;
  title: string;
  shortLabel: string;
  category: SkillCategory;
  kind: "skill" | "education";
  level: string;
  summary: string;
  experience: string[];
  tags: string[];
  tone: "blue" | "peach" | "indigo" | "sage" | "stone" | "mustard" | "violet" | "terracotta";
  height: number;
};

export const shelfLabels: Record<SkillCategory, string> = {
  frontend: "build",
  ai: "AI",
  education: "education + career",
};

export const skillBooks: SkillBookData[] = [
  {
    id: "react",
    title: "React",
    shortLabel: "React",
    category: "frontend",
    kind: "skill",
    level: "Experienced",
    summary: "I use React to build interactive products, portals, and reusable interface systems.",
    experience: ["Contributor portals", "Marketplace interfaces", "Complex forms", "API-driven UI"],
    tags: ["React", "Components", "State", "REST APIs"],
    tone: "blue",
    height: 126,
  },
  {
    id: "astro",
    title: "Astro",
    shortLabel: "Astro",
    category: "frontend",
    kind: "skill",
    level: "Production work",
    summary: "I build fast content and corporate platforms with Astro and headless content workflows.",
    experience: ["Corporate websites", "Job platforms", "Headless CMS work", "Performance-focused builds"],
    tags: ["Astro", "Islands", "CMS", "Performance"],
    tone: "peach",
    height: 116,
  },
  {
    id: "typescript",
    title: "TypeScript",
    shortLabel: "TypeScript",
    category: "frontend",
    kind: "skill",
    level: "Daily toolkit",
    summary: "TypeScript helps me keep larger frontends predictable, maintainable, and easier to evolve.",
    experience: ["Typed component APIs", "Data modelling", "Safer refactors", "Next.js applications"],
    tags: ["TypeScript", "Types", "Architecture"],
    tone: "indigo",
    height: 132,
  },
  {
    id: "tailwind",
    title: "Tailwind CSS",
    shortLabel: "Tailwind",
    category: "frontend",
    kind: "skill",
    level: "Experienced",
    summary: "I use Tailwind to turn design systems into consistent, responsive product interfaces.",
    experience: ["Responsive systems", "Design tokens", "Component styling", "Rapid UI iteration"],
    tags: ["Tailwind", "CSS", "Responsive UI"],
    tone: "sage",
    height: 120,
  },
  {
    id: "wordpress",
    title: "WordPress",
    shortLabel: "WordPress",
    category: "frontend",
    kind: "skill",
    level: "Advanced implementation",
    summary: "I use WordPress beyond page building, including structured content and custom product workflows.",
    experience: ["Custom post types", "ACF content systems", "Custom APIs", "Marketplace workflows"],
    tags: ["WordPress", "ACF", "APIs", "CMS"],
    tone: "indigo",
    height: 138,
  },
  {
    id: "ai",
    title: "Artificial Intelligence",
    shortLabel: "AI",
    category: "ai",
    kind: "skill",
    level: "Research + applied interest",
    summary: "My AI experience comes from machine-learning research and practical chatbot development.",
    experience: ["NLP pipelines", "Chatbot development", "BERT fine-tuning", "ML research"],
    tags: ["AI", "ML", "NLP", "Research"],
    tone: "violet",
    height: 142,
  },
  {
    id: "python",
    title: "Python",
    shortLabel: "Python",
    category: "ai",
    kind: "skill",
    level: "Research toolkit",
    summary: "I use Python for machine-learning experiments, data preparation, and research workflows.",
    experience: ["Model experiments", "Data preparation", "Research notebooks", "NLP pipelines"],
    tags: ["Python", "Data", "ML"],
    tone: "mustard",
    height: 122,
  },
  {
    id: "vibe-coding",
    title: "Vibe Coding",
    shortLabel: "Vibe",
    category: "ai",
    kind: "skill",
    level: "Interest",
    summary: "Vibe Coding is a new approach to AI-assisted coding that uses natural-language prompts to generate code and workflows.",
    experience: ["Natural language prompts", "Code generation", "Workflow automation", "AI-assisted development"],
    tags: ["Vibe Coding", "AI", "Coding"],
    tone: "sage",
    height: 138,
  },
  {
    id: "bsc",
    title: "BSc (Hons) Information Technology",
    shortLabel: "BSc IT",
    category: "education",
    kind: "education",
    level: "SLIIT",
    summary: "A foundation in software engineering, information technology, and practical application development.",
    experience: ["Software engineering", "Web development", "Databases", "Team projects"],
    tags: ["BSc (Hons)", "IT", "SLIIT"],
    tone: "peach",
    height: 136,
  },
  {
    id: "research",
    title: "Research",
    shortLabel: "Research",
    category: "education",
    kind: "education",
    level: "AI + Sentiment Analysis",
    summary: "I have conducted research in natural-language chatbots, including sentiment analysis.",
    experience: ["Chatbot research", "Sentiment analysis", "NLP pipelines", "BERT fine-tuning"],
    tags: ["Research", "Sentiment", "NLP"],
    tone: "violet",
    height: 126,
  },
  {
    id: "experience",
    title: "Software Engineering",
    shortLabel: "4+ years",
    category: "education",
    kind: "education",
    level: "Professional experience",
    summary: "More than five years delivering web products across frontend, CMS, and business-platform work.",
    experience: ["30+ shipped projects", "Frontend systems", "Client delivery", "Product refinement"],
    tags: ["Engineering", "Delivery", "Products"],
    tone: "stone",
    height: 132,
  },
];
